version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: evergreen
      POSTGRES_PASSWORD: evergreen
      POSTGRES_DB: evergreen
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
